apiVersion: batch/v1
kind: CronJob
metadata:
  name: healthcheck-pi4
  labels:
    app: healthchecks-io
spec:
  schedule: "0/15 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      ttlSecondsAfterFinished: 10
      concurrencyPolicy: forbid
      template:
        metadata:
          labels:
            app: healthchecks-io
        spec:
          containers:
          - name: curl
            image: curlimages/curl:7.80.0
            imagePullPolicy: IfNotPresent
            args: ["-f", "$(URL)"]
            env:
            - name: URL
              valueFrom:
                secretKeyRef:
                  name: healthcheck-pi4
                  key: URL
          restartPolicy: OnFailure


