pushgateway:
  enabled: false

  # - job_name: luckystar
  #   static_configs:
  #     - targets:
  #       - luckystar.carlosbecker.dev
extraScrapeConfigs: |
  - job_name: starcharts
    scrape_interval: 1m
    static_configs:
      - targets:
        - starchart.cc
  - job_name: watchub
    scrape_interval: 1m
    static_configs:
      - targets:
        - watchub.pw
  - job_name: redis
    scrape_interval: 1m
    static_configs:
      - targets:
        - s01.caarlos0.dev:9121
  - job_name: confettysh
    scrape_interval: 1m
    static_configs:
      - targets:
        - ssh.caarlos0.dev:9222
  - job_name: fireworksh
    scrape_interval: 1m
    static_configs:
      - targets:
        - ssh.caarlos0.dev:9223
  - job_name: parttysh
    scrape_interval: 1m
    static_configs:
      - targets:
        - ssh.caarlos0.dev:9225

server:
  ingress:
    enabled: true
    hosts:
      - prometheus.homes
  image:
    tag: v2.33.0

  retention: "45d"

  resources:
    limits:
      cpu: 1
      memory: 1.5Gi
    requests:
      cpu: 1
      memory: 1.5Gi


alertmanager:
  enabled: false
