pushgateway:
  enabled: false

extraScrapeConfigs: |
  - job_name: starcharts
    static_configs:
      - targets:
        - starchart.cc
  - job_name: watchub
    static_configs:
      - targets:
        - watchub.pw
  - job_name: redis
    static_configs:
      - targets:
        - s01.caarlos0.dev:9121

server:
  ingress:
    enabled: true
    hosts:
      - prometheus.home
