pushgateway:
  enabled: false

  # - job_name: luckystar
  #   static_configs:
  #     - targets:
  #       - luckystar.carlosbecker.dev
extraScrapeConfigs: |
  - job_name: starcharts
    scrape_interval: 5m
    static_configs:
      - targets:
        - starchart.cc
  - job_name: watchub
    scrape_interval: 5m
    static_configs:
      - targets:
        - watchub.pw
  - job_name: redis
    scrape_interval: 5m
    static_configs:
      - targets:
        - s01.caarlos0.dev:9121

server:
  ingress:
    enabled: true
    hosts:
      - prometheus.home
  image:
    tag: v2.28.1
