apiVersion: v1
kind: Service
metadata:
  name: fastcom-exporter
  namespace: monitoring
  labels:
    app: fastcom-exporter
spec:
  selector:
    app: fastcom-exporter
  ports:
    - protocol: TCP
      port: 9875
      targetPort: 9875
