apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: adguard
  name: adguard
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - host: adguard.homes
    http:
      paths:
      - backend:
          service:
            name: adguard
            port:
              number: 3000
        path: /
        pathType: Prefix
