apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-debug
  name: prometheus-debug
  namespace: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus-debug
  template:
    metadata:
      labels:
        app: prometheus-debug
    spec:
      containers:
      - args: ['sleep', '10m']
        image: alpine
        imagePullPolicy: IfNotPresent
        name: prometheus-server
        volumeMounts:
        - mountPath: /data
          name: storage-volume
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: prometheus-server
