# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.14.0/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-exporter
  namespace: monitoring
  labels:
    app: speedtest-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-exporter
  template:
    metadata:
      labels:
        app: speedtest-exporter
    spec:
      containers:
        - name: speedtest-exporter
          image: ghcr.io/caarlos0/speedtest-exporter:v1.1.3
          args: ["--refresh.interval=6h"]
          ports:
            - containerPort: 9876
      readinessProbe:
        httpGet:
          path: /
          port: 9876
        initialDelaySeconds: 5
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /
          port: 9876
        initialDelaySeconds: 5
        periodSeconds: 5
