apiVersion: v1
kind: Service
metadata:
  name: speedtest-exporter
  nemespace: monitoring
  labels:
    app: speedtest-exporter
spec:
  selector:
    app: speedtest-exporter
  ports:
    - protocol: TCP
      port: 9876
      targetPort: 9876
