apiVersion: v1
kind: Service
metadata:
  name: speedtest-exporter
  nemespace: monitoring
  labels:
    app: speedtest-exporter
  annotations:
    prometheus.io/scrape: true
    prometheus.io/path: /metrics
    prometheus.io/port: 9876
spec:
  selector:
    app: speedtest-exporter
  ports:
    - protocol: TCP
      port: 9876
      targetPort: 9876
