---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Becker's"
subtitle: "Homes"
# logo: "logo.png"
icon: "fas fa-skull-crossbones"

header: true
footer: false

theme: default

services:
  - name: "Networking"
    icon: "fas fa-cloud"
    items:
      - name: "Unify"
        url: https://192.168.1.1/network/default/dashboard
      - name: "NextDNS"
        url: https://my.nextdns.io/cf7c1e/setup
      - name: NAS
        url: http://nas.local:5000

  - name: "TV"
    icon: "fas fa-tv"
    items:
      - name: "Plex"
        url: http://darkstar.local:32400
      - name: "Radarr"
        type: "Radarr"
        url: "http://darkstar.local:7878/"
        apikey: "c921b6e82b49441ebf21c14faa0892f1"
      - name: "Sonarr"
        type: "Sonarr"
        url: "http://darkstar.local:8989/"
        apikey: "d011df2dd51347b68387a7d0bf26bef1"
      - name: Jackett
        url: http://jackett.homes/
      - name: Transmission
        url: http://darkstar.local:9091/transmission/

  - name: "Security"
    icon: "fas fa-video"
    items:
      - name: "Protect"
        url: https://192.168.1.1/protect/dashboard
      - name: "Homebridge"
        url: http://pi4.local:8581/

  - name: "Monitoring"
    icon: "fas fa-chart-simple"
    items:
      - name: "Prometheus"
        type: Prometheus
        url: "http://prometheus.homes/"
      - name: "Grafana"
        url: "http://grafana.homes/"
