apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextdns
  labels:
    app: nextdns
spec:
  schedule: "0/15 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      ttlSecondsAfterFinished: 10
      template:
        metadata:
          labels:
            app: nextdns
        spec:
          containers:
          - name: curl
            image: curlimages/curl:7.80.0 # TODO: update
            envFrom:
            - secretRef:
                name: nextdns
            imagePullPolicy: IfNotPresent
            args: ["-sf", "${NEXTDNS_URL}"]
          restartPolicy: OnFailure


