apiVersion: batch/v1
kind: CronJob
metadata:
  name: deadmansnitch
  labels:
    app: deadmansnitch
spec:
  schedule: "0/15 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      ttlSecondsAfterFinished: 10
      template:
        metadata:
          labels:
            app: deadmansnitch
        spec:
          containers:
          - name: curl
            image: curlimages/curl:7.80.0 # TODO: update
            imagePullPolicy: IfNotPresent
            args: ["-sf", "${SNITCH_URL}"]
            envFrom:
            - secretRef:
                name: deadmansnitch
          restartPolicy: OnFailure


