apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: deadmansnitch
  namespace: default
spec:
  encryptedData:
    SNITCH_URL: AgBoqD/1ArGMxAKKrLnw/Y5kOlP1GysPc/16bhzgrtb9w6KVw98R/JCV7olcoeMPeT5WwTGRwjjzjjexHvOxKkkwTkSswENZuLRUZldkgeO+ULtlKQElmawT4mDXY/SyWlNA8rY07VI4QNPPSvWDs/3lwEmd3PlJz+8tTiAN6P00c+MalKzv7Pa+rbVl4hLG1PcInDJxlTbWLumexCOkhQOz8zCFvSE4Vu12o/Zf8sDEj35zh7TxMTIkG9LlFnkALvYJhpcvX/F9LLqjjUckv9l1f6JUmti4TuIzaL8L8pASNLL6o//l/vSwrfye8iuLMwrEfA9xmKtwoXyiuAlxqwNDaouQVUPwusk9Ibs9HT94fDOOzuME+ybV/oX8llsNzkIFpI5/rj1hQVu04rXBRAvJIPgcAH7HUWB/C0Us3vdqDw0xZUT+FhMO76r9hA4OvZFwtygK6ob1ygWDWy0nkVDgHqjNUQza9f96Cklp5Wfnf8sZfS7UE44y2oGcuHMkqJTW1PlIEGLkbWCMuh2IYztIDm7YGbqdyFQyONiYmhEdqY5GzheUVNuv3BjzDorAbHEgM2Kz07rIW3O2LT3xbZnihhkNXHhDL4BPO1+n/1UqBxscnZGe1CN3jC3y2FxSidxOxhBKOj0Iw5iMD2iIlJq1f+JIe0RYQVJa4aY4yxHbzG+OhpV7MYurZFHM5xvMvaFViviSyMU+0FgOIHGwNvHqJ0b5ZW3+FLv0v+U2
  template:
    metadata:
      creationTimestamp: null
      name: deadmansnitch
      namespace: default
    type: Opaque

