apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  interval: 5m
  chart:
    spec:
      version: "48.x"
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  values:
    alertmanager:
      enabled: false
    grafana:
      dashboards:
        default:
          speedtest:
            gnetId: 14187
            revision: 4
            datasource: Prometheus
      ingress:
        enabled: true
        hosts:
          - grafana.homes
          - grafana.vpn
    prometheus:
      ingress:
        enabled: true
        hosts:
          - prometheus.homes
          - prometheus.vpn
      prometheusSpec:
        retention: 15d
        resources:
          limits:
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 200Mi
        podMonitorNamespaceSelector: {}
        serviceMonitorNamespaceSelector: {}
        podMonitorSelector:
          matchLabels: {}
        serviceMonitorSelector:
          matchLabels: {}
