# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.14.0/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  labels:
    app: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      nodeSelector:
        kubernetes.io/hostname: pi4
      containers:
        - name: jackett
          image: lscr.io/linuxserver/jackett:latest
          ports:
            - containerPort: 9117
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /downloads
              name: downloads
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/Sao_Paulo
      volumes:
        - name: config
          hostPath:
            path: /var/local/jackett/config
            type: DirectoryOrCreate
        - name: downloads
          hostPath:
            path: /var/local/jackett/downloads
            type: DirectoryOrCreate
      readinessProbe:
        httpGet:
          path: /
          port: 9117
        initialDelaySeconds: 5
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /
          port: 9117
        initialDelaySeconds: 5
        periodSeconds: 5
